export enum RoleId {
  MARKETING = 'MARKETING',
  CUSTOMER_SUCCESS = 'CUSTOMER-SUCCESS',
  COMMUNITY_MANAGER = 'COMMUNITY-MANAGER',
  ENGINEERING = 'ENGINEERING',
  PRODUCT = 'PRODUCT',
  OTHER = 'OTHER',
}

export const ROLE_OPTIONS_MAP = {
  [RoleId.MARKETING]: {
    id: RoleId.MARKETING,
    name: 'Marketing',
  },
  [RoleId.CUSTOMER_SUCCESS]: {
    id: RoleId.CUSTOMER_SUCCESS,
    name: 'Customer Success',
  },
  [RoleId.COMMUNITY_MANAGER]: {
    id: RoleId.COMMUNITY_MANAGER,
    name: 'Community Manager',
  },
  [RoleId.ENGINEERING]: {
    id: RoleId.ENGINEERING,
    name: 'Engineering',
  },
  [RoleId.PRODUCT]: {
    id: RoleId.PRODUCT,
    name: 'Product',
  },
  [RoleId.OTHER]: { id: RoleId.OTHER, name: 'Other' },
}

export const ROLE_OPTION_ITEMS = Object.values(ROLE_OPTIONS_MAP).map(role => ({
  name: role.name,
  id: role.id,
}))

export const OTHER_ROLE_ITEMS = [
  { id: 'product-manager', label: 'Product Manager' },
  { id: 'product-owner', label: 'Product Owner' },
  { id: 'marketing-manager', label: 'Marketing Manager' },
  { id: 'marketing-director', label: 'Marketing Director' },
  { id: 'cm-marketing-manager', label: 'CM Marketing Manager' },
  { id: 'brand-manager', label: 'Brand Manager' },
  { id: 'content-manager', label: 'Content Manager' },
  { id: 'social-media-manager', label: 'Social Media Manager' },
  { id: 'community-director', label: 'Community Director' },
  { id: 'head-of-community', label: 'Head of Community' },
  { id: 'vp-community', label: 'VP of Community' },
  { id: 'customer-advocate', label: 'Customer Advocate' },
  { id: 'customer-support', label: 'Customer Support' },
  { id: 'customer-support-manager', label: 'Customer Support Manager' },
  { id: 'customer-experience', label: 'Customer Experience' },
  { id: 'cx-manager', label: 'CX Manager' },
  { id: 'user-success', label: 'User Success' },
  { id: 'developer-advocate', label: 'Developer Advocate' },
  { id: 'developer-relations', label: 'Developer Relations' },
  { id: 'devrel', label: 'DevRel' },
  { id: 'technical-evangelist', label: 'Technical Evangelist' },
  { id: 'founder', label: 'Founder' },
  { id: 'co-founder', label: 'Co-Founder' },
  { id: 'ceo', label: 'CEO' },
  { id: 'cto', label: 'CTO' },
  { id: 'cmo', label: 'CMO' },
  { id: 'cpo', label: 'CPO' },
  { id: 'vp-marketing', label: 'VP of Marketing' },
  { id: 'vp-product', label: 'VP of Product' },
  { id: 'director-marketing', label: 'Director of Marketing' },
  { id: 'director-product', label: 'Director of Product' },
  { id: 'director-community', label: 'Director of Community' },
  { id: 'operations-manager', label: 'Operations Manager' },
  { id: 'operations-director', label: 'Operations Director' },
  { id: 'program-manager', label: 'Program Manager' },
  { id: 'project-manager', label: 'Project Manager' },
  { id: 'event-manager', label: 'Event Manager' },
  { id: 'event-coordinator', label: 'Event Coordinator' },
  { id: 'community-coordinator', label: 'Community Coordinator' },
  { id: 'community-specialist', label: 'Community Specialist' },
  { id: 'community-associate', label: 'Community Associate' },
  { id: 'marketing-specialist', label: 'Marketing Specialist' },
  { id: 'marketing-coordinator', label: 'Marketing Coordinator' },
  { id: 'marketing-associate', label: 'Marketing Associate' },
  { id: 'content-creator', label: 'Content Creator' },
  { id: 'content-strategist', label: 'Content Strategist' },
  { id: 'content-writer', label: 'Content Writer' },
  { id: 'copywriter', label: 'Copywriter' },
  { id: 'seo-specialist', label: 'SEO Specialist' },
  { id: 'ppc-specialist', label: 'PPC Specialist' },
  { id: 'email-marketing', label: 'Email Marketing Manager' },
  { id: 'demand-generation', label: 'Demand Generation Manager' },
  { id: 'growth-hacker', label: 'Growth Hacker' },
  { id: 'growth-lead', label: 'Growth Lead' },
  { id: 'acquisition-manager', label: 'Acquisition Manager' },
  { id: 'retention-manager', label: 'Retention Manager' },
  { id: 'engagement-manager', label: 'Engagement Manager' },
  { id: 'analyst', label: 'Analyst' },
  { id: 'data-analyst', label: 'Data Analyst' },
  { id: 'business-analyst', label: 'Business Analyst' },
  { id: 'marketing-analyst', label: 'Marketing Analyst' },
  { id: 'researcher', label: 'Researcher' },
  { id: 'ux-researcher', label: 'UX Researcher' },
  { id: 'user-researcher', label: 'User Researcher' },
  { id: 'designer', label: 'Designer' },
  { id: 'ux-designer', label: 'UX Designer' },
  { id: 'ui-designer', label: 'UI Designer' },
  { id: 'product-designer', label: 'Product Designer' },
  { id: 'developer', label: 'Developer' },
  { id: 'software-engineer', label: 'Software Engineer' },
  { id: 'frontend-developer', label: 'Frontend Developer' },
  { id: 'backend-developer', label: 'Backend Developer' },
  { id: 'fullstack-developer', label: 'Fullstack Developer' },
  { id: 'consultant', label: 'Consultant' },
  { id: 'freelancer', label: 'Freelancer' },
  { id: 'contractor', label: 'Contractor' },
  { id: 'intern', label: 'Intern' },
  { id: 'student', label: 'Student' },
  { id: 'other', label: 'Other' },
]
